### ISSUE TITLE
Design Docs Sample State Review

### ISSUE THREAD

**Issue by rlim92** [pauchye/ASTRA#2]
Hey Olga! The sample state is looking good. A few suggestions below.

**Sample State**
- [x] for `routes created` and `route id` make sure to include the underscore (`_`) or make it camelCase in the jbuilder view. 
- [x] `pictures` will be some path to AWS site hosting the photo
- [x] make sure `errors` and `session` slice of state is at the same top level as `entities` and `ui`. They are their own slice of state.

**Comment by pauchye** [comment]
hi Rich, i would like to discuss the db a little bit. It looks like the real strava does not have a direct association between routes and workouts. as far as i understand you create a route and strava navigates you while you are running. when you are running gps tracking creates the map. i think it make sense to add route to the workout so that we can add the map to the feed and that is all.

**Comment by rlim92** [comment]
Hey Olga, okay got it. That sounds good to me. 👍
